SELECT ID, EMAIL, PASSWORD, NAME, REGDATE FROM MEMBER;

SELECT ID, EMAIL, PASSWORD, NAME, REGDATE FROM MEMBER WHERE EMAIL = 'test@test.co.kr';

UPDATE MEMBER SET EMAIL WHERE id = ?;

DELETE FROM 'MEMBER' WHERE id = ?;
