SELECT ID, EMAIL, PASSWORD, NAME, REGDATE FROM MEMBER;

SELECT ID, EMAIL, PASSWORD, NAME, REGDATE FROM MEMBER WHERE EMAIL = 'test@test.co.kr';

UPDATE MEMBER SET EMAIL WHERE id = ?;

DELETE FROM 'MEMBER' WHERE id = ?;

SELECT ID, EMAIL, PASSWORD, NAME, REGDATE
  FROM MEMBER
 WHERE REGDATE BETWEEN '2020-09-01' AND '2020-09-30'
 ORDER BY REGDATE DESC;
